[tool.poetry]
name = "nr-openai-observability"
version = "0.1.0"
description = ""
authors = ["AIR <applied-intelligence-research-team@newrelic.com>"]

[tool.poetry.dependencies]
python = "^3.8"
newrelic-telemetry-sdk = "^0.4.3"
openai = "^0.26.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"


[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
